CARD_SCALE = 2
CARD_WIDTH = 350 * CARD_SCALE
CARD_HEIGHT = 450 * CARD_SCALE
CARD_SIZE = (CARD_WIDTH, CARD_HEIGHT)
EDGE_MARGIN = 10 * CARD_SCALE
IMAGE_WIDTH = CARD_WIDTH - (2 * EDGE_MARGIN)
IMAGE_HEIGHT = CARD_HEIGHT - (2 * EDGE_MARGIN)
DIE_SPACING = 0.7
